//AUTOGENERATED FILE FROM png2asset
// Conversion args: \famidash_chr_gb.png -bpp 2 -tiles_only -keep_duplicate_tiles -sprite_no_optimize -noflip -bin -map -o \famidash_chr.bin

#ifndef METASPRITE_famidash_chr_H
#define METASPRITE_famidash_chr_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define famidash_chr_TILE_ORIGIN 0
#define famidash_chr_TILE_W 8
#define famidash_chr_TILE_H 8
#define famidash_chr_WIDTH 128
#define famidash_chr_HEIGHT 128
#define famidash_chr_TILE_COUNT 256
#define famidash_chr_PALETTE_COUNT 1
#define famidash_chr_COLORS_PER_PALETTE 4
#define famidash_chr_TOTAL_COLORS 4

BANKREF_EXTERN(famidash_chr)

extern const palette_color_t famidash_chr_palettes[4];
extern const uint8_t famidash_chr_tiles[4096];

#endif
