//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gb_tiles_H
#define METASPRITE_gb_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gb_tiles_TILE_ORIGIN 0
#define gb_tiles_TILE_W 8
#define gb_tiles_TILE_H 8
#define gb_tiles_WIDTH 176
#define gb_tiles_HEIGHT 48
#define gb_tiles_TILE_COUNT 31
#define gb_tiles_PALETTE_COUNT 1
#define gb_tiles_COLORS_PER_PALETTE 4
#define gb_tiles_TOTAL_COLORS 4
#define gb_tiles_MAP_ATTRIBUTES 0
extern const unsigned char gb_tiles_map[132];
#define gb_tiles_map_attributes gb_tiles_map

BANKREF_EXTERN(gb_tiles)

extern const palette_color_t gb_tiles_palettes[4];
extern const uint8_t gb_tiles_tiles[496];

#endif
