#ifndef STEREOMADNESS_BG_H
#define STEREOMADNESS_BG_H

#include <stdint.h>

#define STEREOMADNESS_BG_WIDTH 894
#define STEREOMADNESS_BG_HEIGHT 27
#define STEREOMADNESS_BG_TILE_WIDTH (STEREOMADNESS_BG_WIDTH * 2)
#define STEREOMADNESS_BG_TILE_HEIGHT (STEREOMADNESS_BG_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* STEREOMADNESS_BG_H */
