#ifndef STEREOMADNESS_SCREEN3_H
#define STEREOMADNESS_SCREEN3_H

#include <stdint.h>

#define STEREOMADNESS_SCREEN3_WIDTH 10
#define STEREOMADNESS_SCREEN3_HEIGHT 9
#define STEREOMADNESS_SCREEN3_TILE_WIDTH (STEREOMADNESS_SCREEN3_WIDTH * 2)
#define STEREOMADNESS_SCREEN3_TILE_HEIGHT (STEREOMADNESS_SCREEN3_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* STEREOMADNESS_SCREEN3_H */
