#ifndef STEREOMADNESS_SCREEN0_H
#define STEREOMADNESS_SCREEN0_H

#include <stdint.h>

#define STEREOMADNESS_SCREEN0_WIDTH 10
#define STEREOMADNESS_SCREEN0_HEIGHT 9
#define STEREOMADNESS_SCREEN0_TILE_WIDTH (STEREOMADNESS_SCREEN0_WIDTH * 2)
#define STEREOMADNESS_SCREEN0_TILE_HEIGHT (STEREOMADNESS_SCREEN0_HEIGHT * 2)

extern const uint8_t level_map[];

#endif /* STEREOMADNESS_SCREEN0_H */
